
package com.ricky.client_with_wsimport;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloMessage", targetNamespace = "http://service.ricky.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloMessage {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.ricky.com/HelloMessage/getMessageRequest", output = "http://service.ricky.com/HelloMessage/getMessageResponse")
    public String getMessage();

}
