
package com.ricky.client_with_wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloMessageImplService", targetNamespace = "http://service.ricky.com/", wsdlLocation = "http://localhost:9999/ws/hello?wsdl")
public class HelloMessageImplService
    extends Service
{

    private final static URL HELLOMESSAGEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOMESSAGEIMPLSERVICE_EXCEPTION;
    private final static QName HELLOMESSAGEIMPLSERVICE_QNAME = new QName("http://service.ricky.com/", "HelloMessageImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOMESSAGEIMPLSERVICE_WSDL_LOCATION = url;
        HELLOMESSAGEIMPLSERVICE_EXCEPTION = e;
    }

    public HelloMessageImplService() {
        super(__getWsdlLocation(), HELLOMESSAGEIMPLSERVICE_QNAME);
    }

    public HelloMessageImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOMESSAGEIMPLSERVICE_QNAME, features);
    }

    public HelloMessageImplService(URL wsdlLocation) {
        super(wsdlLocation, HELLOMESSAGEIMPLSERVICE_QNAME);
    }

    public HelloMessageImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOMESSAGEIMPLSERVICE_QNAME, features);
    }

    public HelloMessageImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloMessageImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloMessage
     */
    @WebEndpoint(name = "HelloMessageImplPort")
    public HelloMessage getHelloMessageImplPort() {
        return super.getPort(new QName("http://service.ricky.com/", "HelloMessageImplPort"), HelloMessage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloMessage
     */
    @WebEndpoint(name = "HelloMessageImplPort")
    public HelloMessage getHelloMessageImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ricky.com/", "HelloMessageImplPort"), HelloMessage.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOMESSAGEIMPLSERVICE_EXCEPTION!= null) {
            throw HELLOMESSAGEIMPLSERVICE_EXCEPTION;
        }
        return HELLOMESSAGEIMPLSERVICE_WSDL_LOCATION;
    }

}
